# Generated by Django 4.2.19 on 2025-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0003_alter_artist_options_album_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
