# Generated by Django 4.2.19 on 2025-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0004_track_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
