# Generated by Django 4.2.19 on 2025-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0005_track_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
