# Generated by Django 4.2.19 on 2025-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0006_track_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default='Bio not provided'),
            preserve_default=False,
        ),
    ]
