# Generated by Django 4.2.19 on 2025-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0007_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='tracks/default.mp3', upload_to='tracks/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(default='tracks/default.mp3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
