# Generated by Django 4.2.19 on 2025-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0008_track_audio_file_track_description_track_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='tracks/default.mp3', upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
