# Generated by Django 4.2.19 on 2025-03-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0009_alter_track_audio_file_alter_track_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/'),
        ),
    ]
