# Generated by Django 4.2.19 on 2025-03-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0010_alter_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicHub_App.artist'),
        ),
    ]
