# Generated by Django 4.2.19 on 2025-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0011_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
