# Generated by Django 4.2.19 on 2025-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0012_track_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='album_avatars/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='artist_avatars/'),
        ),
        migrations.AddField(
            model_name='track',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='track_avatars/'),
        ),
    ]
