# Generated by Django 4.2.19 on 2025-03-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHub_App', '0013_album_avatar_artist_avatar_track_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='avatar',
        ),
    ]
